"""Initial encrypted patient records, clinical drafts, and audit tables."""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_owner_id"), "patients", ["owner_id"], unique=False)
    op.create_table(
        "rate_buckets",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("reset_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_rate_buckets_reset_at"), "rate_buckets", ["reset_at"], unique=False)
    op.create_table(
        "consultations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("doctor_id", sa.String(length=128), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consultations_created_at"), "consultations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_consultations_doctor_id"), "consultations", ["doctor_id"], unique=False
    )
    op.create_index(op.f("ix_consultations_owner_id"), "consultations", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_consultations_patient_id"), "consultations", ["patient_id"], unique=False
    )
    op.create_table(
        "ai_analysis_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_analysis_records_consultation_id"),
        "ai_analysis_records",
        ["consultation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_analysis_records_input_hash"),
        "ai_analysis_records",
        ["input_hash"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("file_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_consultation_id"), "documents", ["consultation_id"], unique=False
    )
    op.create_table(
        "prescriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("consultation_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("pdf", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["ai_analysis_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_hash"),
    )
    op.create_index(
        op.f("ix_prescriptions_consultation_id"), "prescriptions", ["consultation_id"], unique=False
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # Only the backend DB role can access these tables. No Supabase Data API policies.
        for table in (
            "patients",
            "consultations",
            "ai_analysis_records",
            "documents",
            "prescriptions",
            "audit_events",
            "rate_buckets",
        ):
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"REVOKE ALL ON TABLE {table} FROM PUBLIC")
            for role in ("anon", "authenticated"):
                op.execute(
                    f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN EXECUTE 'REVOKE ALL ON TABLE {table} FROM {role}'; END IF; END $$"
                )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prescriptions_consultation_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    op.drop_index(op.f("ix_documents_consultation_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_ai_analysis_records_input_hash"), table_name="ai_analysis_records")
    op.drop_index(op.f("ix_ai_analysis_records_consultation_id"), table_name="ai_analysis_records")
    op.drop_table("ai_analysis_records")
    op.drop_index(op.f("ix_consultations_patient_id"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_owner_id"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_doctor_id"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_created_at"), table_name="consultations")
    op.drop_table("consultations")
    op.drop_index(op.f("ix_rate_buckets_reset_at"), table_name="rate_buckets")
    op.drop_table("rate_buckets")
    op.drop_index(op.f("ix_patients_owner_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
